# Schema validator for the quality_control
# author: Thomas Cokelaer

type: map
mapping:
    "sequana_wrappers":
        type: str
        required: true
    "input_directory":
        type: str
        required: True
    "input_readtag":
        type: str
        required: False
    "input_pattern":
        type: str
        required: True

    "apptainers":
        type: any

    "general":
        type: map
        mapping:
            "mapper":
                type: str
                enum: [bwa, minimap2, bowtie2, bwa_split]
            "reference_file":
                type: str
            "annotation_file":
                type: str
            "create_bigwig":
                type: bool

    "bwa_split":
        type: map
        mapping:
            "nreads":
                type: int 
            "index_algorithm":
                type: str 
            "options":
                type: str 
            "threads":
                type: int 
            "tmp_directory":
                type: str 
            "resources":
                 type: map
                 mapping:
                     "mem":
                        type: str
    "bwa":
        type: map
        mapping:
            "index_algorithm":
                type: str 
            "options":
                type: str 
            "threads":
                type: int 
            "tmp_directory":
                type: str 
            "resources":
                 type: map
                 mapping:
                     "mem":
                        type: str

    "multiqc":
        type: map
        mapping:
            "options":
                type: str
            "modules":
                type: str
            "config_file":
                type: str
            "input_directory":
                type: str
            "resources":
                 type: map
                 mapping:
                     "mem":
                        type: str

    "minimap2": 
        type: map
        mapping:
            "options":
                type: str
            "threads": 
                type: int
                range: { min: 1 }
            "resources":
                 type: map
                 mapping:
                     "mem":
                        type: str

    "sequana_coverage":
        type: map
        mapping:
            "do":
                type: bool
                default: False
                required: True
            "circular":
                type: bool
                default: True
                required: True
            "double_threshold":
                type: float
                range: { min: 0, max: 1}
                required: False
                default: 0.5
            "genbank_file":
                type: str
                required: False
            "high_threshold":
                type: float
                range: { min: 2 }
            "low_threshold":
                type: float
                range: { max: -2 }
            "mixture_models":
                type: int
                required: True
                range: { min: 1, max: 3 }
            "reference_file":
                type: str
                required: False
            "chunksize":
                type: int
                required: False
                default: 5000000
            "window_size":
                default: 20001
                type: int
                range: { min: 3 }
            "binning":
                type: int
                range: { min: -1 }
            "cnv_clustering":
                type: int
                range: { min: -1 }
            "gc_window_size":
                type: int
                range: { min: 2}
            "options":
              type: str
            "resources":
                 type: map
                 mapping:
                     "mem":
                        type: str

    "bowtie2":
        type: map
        mapping:
            "options": 
                type: str
            "threads": 
                type: int
                range: { min: 1 }
            "resources":
                 type: map
                 mapping:
                     "mem":
                        type: str

    "bowtie2_index":
        type: map
        mapping:
            "options": 
                type: str
            "threads": 
                type: int
                range: { min: 1 }
            "resources":
                 type: map
                 mapping:
                     "mem":
                        type: str

    "bwa_index":
        type: map
        mapping:
            "options": 
                type: str
            "threads": 
                type: int
                range: { min: 1 }
            "resources":
                 type: map
                 mapping:
                     "mem":
                        type: str

    "feature_counts":
        type: map
        mapping:
            "do":
              type: bool
            "options":
                type: str
            "gff":
                type: str
            "feature":
                type: str
            "attribute":
                type: str
            "threads":
                type: int
                range: { min: 1 }
            "resources":
                 type: map
                 mapping:
                     "mem":
                        type: str

    "samtools_depth":
        type: map
        mapping:
            "max_depth":
                type: int
                range: { min: 1 }
            "resources":
                 type: map
                 mapping:
                     "mem":
                        type: str
    "bam_indexing":
        type: map
        mapping:
            "resources":
                 type: map
                 mapping:
                     "mem":
                        type: str
    "bam2bigwig":
        type: map
        mapping:
            "resources":
                 type: map
                 mapping:
                     "mem":
                        type: str

    "bamtools_stats":
        type: map
        mapping:
            "resources":
                 type: map
                 mapping:
                     "mem":
                        type: str

    "filtering_bam":
        type: map
        mapping:
            "resources":
                 type: map
                 mapping:
                     "mem":
                        type: str
